name: SFH-Hypnotherapy
favicon: null
layout_spectrum: 0.016864192904904485
typography_spectrum: 0.09912507538683712
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.15797165990807116
  lightness: 0.027762353187426925
  saturation: 0.47940722410567105
  rhythmicContrast: 0.6010879543609917
purpose: []
